### ISSUE TITLE
Failing to login

### ISSUE THREAD

**Issue by zachsteffens** [dchesterton/amcrest2mqtt#24]
When I startup the container I'm getting a login error 

```
01/07/2021 23:38:14 [INFO] App Version: 1.0.5
01/07/2021 23:38:14 [INFO] Fetching camera details...
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/amcrest/http.py", line 114, in _generate_token
    resp = self._command(cmd).content.decode('utf-8')
  File "/usr/local/lib/python3.9/site-packages/amcrest/http.py", line 203, in _command
    raise LoginError
amcrest.exceptions.LoginError
```

i'm running docker compose 2.1 and my compose looks like so

```
amcrest2mqtt:
    container_name: amcrest2mtt
    image: dchesterton/amcrest2mqtt:latest
    restart: unless-stopped
    environment:
      AMCREST_HOST: 192.168.1.142
      AMCREST_PASSWORD: myCameraPassword
      MQTT_HOST: 192.168.1.67
      MQTT_USERNAME: mqttUser
      MQTT_PASSWORD: mqttPass
      HOME_ASSISTANT: "true"
```

I know that I've got the IP and the password correct, I used them to connect to the camera via Blue Iris.
Am I missing something?

**Comment by zachsteffens** [comment]
Figured it out. The password had a special character in it that was messing up the docker compose somehow
lets say the original password looked like this
`x$sometexthere*4`
when i viewed the environment for the container in portainer the AMCREST_PASSWORD value was listed as 
`x*4`
It appears that the combination of $ and * were causing a problem with the environment var value and they were just being ignored.

So I changed the password of the camera to something without special characters and it worked perfectly.
