### ISSUE TITLE
[ERROR] Error fetching camera details

### ISSUE THREAD

**Issue by ktoms71** [dchesterton/amcrest2mqtt#80]
Using pull 1.0.16 and confirmed the password to my AD110 camera.   Also confirmed the IP address of the camera, per the Amcrest app.  It appears to connect per the line in the log stating [INFO], but then logs the Error fetching camera details.    I have no other information to provide.   I have the latest firmware on the camera and can access the camera from the Amcrest app.    I've also rebooted the camera numerous times but to no avail.   Any thoughts?    I also tried pull 1.0.15 and have the same issues. 

16/07/2022 00:44:48 [INFO] Fetching camera details...
16/07/2022 00:44:48 [ERROR] Error fetching camera details

**Comment by jwynn6** [comment]
Having the same issues with an AD410 as well.

**Comment by McDAlexander** [comment]
I was seeing the same issue with my setup. I simplified my password (I had special characters in use like #) for the doorbell and everything started working.

**Comment by stefanthoss** [comment]
The string `Fetching camera details...` is printed regardless whether the application was able to connect to the camera or not.

I had the same issue with my AD410 as you and was able to fix it by escaping special characters in the docker-compose file (replace `$` with `$$`). So I went from

```
    environment:
      AMCREST_PASSWORD: cka$wuenyrca$weyr
```

to

```
    environment:
      AMCREST_PASSWORD: "cka$$wuenyrca$$weyr"
```

and it started connecting.

**Comment by DayRunner131** [comment]
Contact Amcrest for a current firmware as their mobile app is not pushing the most current. ...R.20210712 fixed my issues on the AD110 which were similar.

**Comment by nielseulink** [comment]
Possible to share it with us here ?

**Comment by nielseulink** [comment]
> Contact Amcrest for a current firmware as their mobile app is not pushing the most current. ...R.20210712 fixed my issues on the AD110 which were similar.

Could you share it with us?

**Comment by ktoms71** [comment]
I was able to resolve with a factory reset of the doorbell.    So it would appear that some aspect of the hardware had change via a glitch.   To no fault of the a2m component.

**Comment by DayRunner131** [comment]
> > Contact Amcrest for a current firmware as their mobile app is not pushing the most current. ...R.20210712 fixed my issues on the AD110 which were similar.
> 
> Could you share it with us?

Sure, see attached. They warned me that it's only for the AD110 and that they're working on the bug fix for the FW update issue on the mobile app. You'll need their IP Config Tool to upload this file to the AD110.

Keep us posted if this fixes your issues.
[Amcrest_DB-LEXUS_Eng_N_16M_V1.000.00AC008.1.R.20210712.bin.zip](https://github.com/dchesterton/amcrest2mqtt/files/9284216/Amcrest_DB-LEXUS_Eng_N_16M_V1.000.00AC008.1.R.20210712.bin.zip)
.

**Comment by Aersaud** [comment]
I am also experiencing this issue and would like to add more information via my docker logs.


```
amcrest2mqtt-doorbell | <Unconnected @ 172.30.1.148> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='172.30.1.148', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 111] Connection refused'))"))
amcrest2mqtt-doorbell | 10/11/2022 23:42:18 [ERROR] Error fetching camera details
amcrest2mqtt-doorbell | 10/11/2022 23:42:21 [INFO] App Version: 1.0.16
amcrest2mqtt-doorbell | 10/11/2022 23:42:21 [INFO] Fetching camera details...
amcrest2mqtt-doorbell | 10/11/2022 23:42:26 [INFO] Device type: AD410
amcrest2mqtt-doorbell | 10/11/2022 23:42:26 [INFO] Serial number: Z17A5F8986C56
amcrest2mqtt-doorbell | 10/11/2022 23:42:26 [INFO] Software version: 1.000.0000000.7.R (2021-02-20)
amcrest2mqtt-doorbell | 10/11/2022 23:42:26 [INFO] Device name: Front Door
amcrest2mqtt-doorbell | 10/11/2022 23:42:26 [INFO] Fetching storage sensors...
amcrest2mqtt-doorbell | Traceback (most recent call last):
amcrest2mqtt-doorbell |   File "/app/amcrest2mqtt.py", line 416, in <module>
amcrest2mqtt-doorbell |     refresh_storage_sensors()
amcrest2mqtt-doorbell |   File "/app/amcrest2mqtt.py", line 99, in refresh_storage_sensors
amcrest2mqtt-doorbell |     mqtt_publish(topics["storage_used"], to_gb(storage["used"]))
amcrest2mqtt-doorbell |   File "/app/amcrest2mqtt.py", line 105, in to_gb
amcrest2mqtt-doorbell |     return str(round(float(total[0]) / 1024 / 1024 / 1024, 2))
amcrest2mqtt-doorbell | ValueError: could not convert string to float: 'unknown'

```

This issue is usually resolved by bringing the container down and back up for a while before it returns.

**Comment by Aersaud** [comment]
I am also experiencing this issue and would like to add more information via my docker logs.


```
amcrest2mqtt-doorbell | <Unconnected @ 172.30.1.148> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='172.30.1.148', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 111] Connection refused'))"))
amcrest2mqtt-doorbell | 10/11/2022 23:42:18 [ERROR] Error fetching camera details
amcrest2mqtt-doorbell | 10/11/2022 23:42:21 [INFO] App Version: 1.0.16
amcrest2mqtt-doorbell | 10/11/2022 23:42:21 [INFO] Fetching camera details...
amcrest2mqtt-doorbell | 10/11/2022 23:42:26 [INFO] Device type: AD410
amcrest2mqtt-doorbell | 10/11/2022 23:42:26 [INFO] Serial number: [REDACTED]
amcrest2mqtt-doorbell | 10/11/2022 23:42:26 [INFO] Software version: 1.000.0000000.7.R (2021-02-20)
amcrest2mqtt-doorbell | 10/11/2022 23:42:26 [INFO] Device name: Front Door
amcrest2mqtt-doorbell | 10/11/2022 23:42:26 [INFO] Fetching storage sensors...
amcrest2mqtt-doorbell | Traceback (most recent call last):
amcrest2mqtt-doorbell |   File "/app/amcrest2mqtt.py", line 416, in <module>
amcrest2mqtt-doorbell |     refresh_storage_sensors()
amcrest2mqtt-doorbell |   File "/app/amcrest2mqtt.py", line 99, in refresh_storage_sensors
amcrest2mqtt-doorbell |     mqtt_publish(topics["storage_used"], to_gb(storage["used"]))
amcrest2mqtt-doorbell |   File "/app/amcrest2mqtt.py", line 105, in to_gb
amcrest2mqtt-doorbell |     return str(round(float(total[0]) / 1024 / 1024 / 1024, 2))
amcrest2mqtt-doorbell | ValueError: could not convert string to float: 'unknown'

```

This issue is usually resolved by bringing the container down and back up. It will continue to work for a while before the error returns.
To add one to this the doorbell (AD410) in my case does stay connected to the wifi the entire time and is available for streaming via the actual Amcrest Smart Home app.
