### ISSUE TITLE
501 Server Error on AD110 and NA Entities in HA

### ISSUE THREAD

**Issue by DayRunner131** [dchesterton/amcrest2mqtt#82]
Installed v1.0.16. Receiving the following errors. A 501 server error on container start, and async_generator errors when doorbell is rung. Rebooting doorbell & container does not improve the situation.

`28/07/2022 19:10:58 [INFO] {'Code': 'AlarmLocal', 'action': 'Start', 'index': '6'}
28/07/2022 19:10:58 [INFO] {'Code': 'AlarmLocal', 'action': 'Start', 'index': '7'}
28/07/2022 19:11:01 [INFO] {'Code': 'AlarmLocal', 'action': 'Stop', 'index': '6'}
28/07/2022 19:11:02 [INFO] {'Code': 'AlarmLocal', 'action': 'Stop', 'index': '7'}
28/07/2022 19:11:05 [INFO] {'Code': 'AlarmLocal', 'action': 'Start', 'index': '7'}
28/07/2022 19:11:06 [INFO] {'Code': 'AlarmLocal', 'action': 'Start', 'index': '6'}
28/07/2022 19:11:08 [INFO] {'Code': 'AlarmLocal', 'action': 'Stop', 'index': '7'}
28/07/2022 19:11:14 [INFO] {'Code': 'UpdateFile', 'action': 'Pulse', 'index': '0'}
28/07/2022 19:11:14 [INFO] {'Code': 'HotPlug', 'action': 'Pulse', 'index': '0'}
28/07/2022 19:11:16 [INFO] {'Code': 'AlarmLocal', 'action': 'Stop', 'index': '6'}
28/07/2022 19:11:23 [INFO] {'Code': 'VideoMotion', 'action': 'Stop', 'index': '0'}
28/07/2022 19:12:03 [INFO] Exiting app...
28/07/2022 19:12:07 [INFO] App Version: 1.0.16
28/07/2022 19:12:07 [INFO] Fetching camera details...
28/07/2022 19:12:09 [INFO] Device type: AD110
28/07/2022 19:12:09 [INFO] Serial number: ##Removed##
28/07/2022 19:12:09 [INFO] Software version: 1.000.00AC003.0.R (2019-11-13)
28/07/2022 19:12:09 [INFO] Device name: Front Door
28/07/2022 19:12:09 [INFO] Writing Home Assistant discovery config...
28/07/2022 19:12:09 [INFO] Fetching storage sensors...
<Front Door:##SN##> Trying again due to error: HTTPError('501 Server Error: Not Implemented for url: http://192.168.1.203:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')
<Front Door:##SN##> Trying again due to error: HTTPError('501 Server Error: Not Implemented for url: http://192.168.1.203:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')
<Front Door:##SN##> Trying again due to error: HTTPError('501 Server Error: Not Implemented for url: http://192.168.1.203:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')
28/07/2022 19:12:10 [WARNING] Error fetching storage information 501 Server Error: Not Implemented for url: http://192.168.1.203:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo
28/07/2022 19:12:10 [INFO] Listening for events...
28/07/2022 19:12:47 [INFO] {'Code': 'VideoMotion', 'action': 'Start', 'index': '0'}
28/07/2022 19:12:48 [INFO] {'Code': 'AlarmLocal', 'action': 'Start', 'index': '6'}
28/07/2022 19:12:50 [INFO] {'Code': 'AlarmLocal', 'action': 'Start', 'index': '7'}
28/07/2022 19:12:52 [INFO] {'Code': 'UpdateFile', 'action': 'Pulse', 'index': '0'}
28/07/2022 19:12:52 [INFO] {'Code': 'NewFile', 'action': 'Pulse', 'index': '1936614731'}
28/07/2022 19:12:52 [INFO] {'Code': 'UpdateFile', 'action': 'Pulse', 'index': '0'}
28/07/2022 19:12:52 [INFO] {'Code': 'NewFile', 'action': 'Pulse', 'index': '34234187'}
28/07/2022 19:12:55 [INFO] {'Code': 'AlarmLocal', 'action': 'Stop', 'index': '7'}
28/07/2022 19:12:55 [INFO] {'Code': 'AlarmLocal', 'action': 'Stop', 'index': '6'}
28/07/2022 19:12:58 [INFO] {'Code': 'AlarmLocal', 'action': 'Start', 'index': '6'}
28/07/2022 19:13:01 [INFO] {'Code': 'AlarmLocal', 'action': 'Stop', 'index': '6'}
28/07/2022 19:13:01 [INFO] {'Code': 'UpdateFile', 'action': 'Pulse', 'index': '0'}
28/07/2022 19:13:01 [INFO] {'Code': 'NewFile', 'action': 'Pulse', 'index': '34255631'}
28/07/2022 19:13:04 [INFO] {'Code': 'AlarmLocal', 'action': 'Start', 'index': '6'}
28/07/2022 19:13:04 [INFO] {'Code': 'AlarmLocal', 'action': 'Start', 'index': '7'}
28/07/2022 19:13:07 [INFO] {'Code': 'AlarmLocal', 'action': 'Stop', 'index': '6'}
28/07/2022 19:13:08 [INFO] {'Code': 'UpdateFile', 'action': 'Pulse', 'index': '0'}
28/07/2022 19:13:08 [INFO] {'Code': 'NewFile', 'action': 'Pulse', 'index': '1936614730'}
28/07/2022 19:13:08 [INFO] {'Code': 'AlarmLocal', 'action': 'Stop', 'index': '7'}
28/07/2022 19:13:08 [INFO] {'Code': 'UpdateFile', 'action': 'Pulse', 'index': '0'}
28/07/2022 19:13:08 [INFO] {'Code': 'NewFile', 'action': 'Pulse', 'index': '34234186'}
28/07/2022 19:13:11 [INFO] {'Code': 'AlarmLocal', 'action': 'Start', 'index': '6'}
28/07/2022 19:13:11 [INFO] {'Code': 'AlarmLocal', 'action': 'Start', 'index': '7'}
an error occurred during closing of asynchronous generator <async_generator object Http._async_stream_command at 0x7f02c8c29820>
asyncgen: <async_generator object Http._async_stream_command at 0x7f02c8c29820>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/app/amcrest2mqtt.py", line 430, in main
    doorbell_payload = "on" if payload["data"]["Action"] == "Invite" else "off"
KeyError: 'data'

During handling of the above exception, another exception occurred:

RuntimeError: aclose(): asynchronous generator is already running
an error occurred during closing of asynchronous generator <async_generator object Http.async_stream_command at 0x7f02c8c29790>
asyncgen: <async_generator object Http.async_stream_command at 0x7f02c8c29790>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/app/amcrest2mqtt.py", line 430, in main
    doorbell_payload = "on" if payload["data"]["Action"] == "Invite" else "off"
KeyError: 'data'

During handling of the above exception, another exception occurred:

RuntimeError: aclose(): asynchronous generator is already running
an error occurred during closing of asynchronous generator <async_generator object AsyncClient.stream at 0x7f02c88a4f70>
asyncgen: <async_generator object AsyncClient.stream at 0x7f02c88a4f70>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/app/amcrest2mqtt.py", line 430, in main
    doorbell_payload = "on" if payload["data"]["Action"] == "Invite" else "off"
KeyError: 'data'

During handling of the above exception, another exception occurred:

RuntimeError: aclose(): asynchronous generator is already running
Traceback (most recent call last):
  File "/app/amcrest2mqtt.py", line 440, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/app/amcrest2mqtt.py", line 430, in main
    doorbell_payload = "on" if payload["data"]["Action"] == "Invite" else "off"
KeyError: 'data'`

**Comment by DayRunner131** [comment]
These 501 and async errors were fixed when AD110 firmware v.1.000.00AC008.1.R.20210712 was pushed to device. Note, Amcrest noted to me that their app has a bug and will not display the correct current firmware, so it must be pushed by their desktop app.
